# Disable compfix for sudo su
ZSH_DISABLE_COMPFIX=true

fpath=("$HOME/.shell/zsh" $fpath)

set -o vi

source ~/.shell/zsh/dirpersist.plugin.zsh
source ~/.shell/zsh/git-auto-status.plugin.zsh

[ -d "$HOME/GIT/config/zsh-autosuggestions" ] || { mkdir -p $HOME/GIT/config && git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/GIT/config/zsh-autosuggestions }
source ~/GIT/config/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -d "$HOME/GIT/config/zsh-z" ] || { mkdir -p $HOME/GIT/config && git clone git@github.com:agkozak/zsh-z.git $HOME/GIT/config/zsh-z }
source ~/GIT/config/zsh-z/zsh-z.plugin.zsh
ZSHZ_CASE=smart

[ -d "$HOME/GIT/config/zsh-history-substring-search" ] || { mkdir -p $HOME/GIT/config && git clone git@github.com:zsh-users/zsh-history-substring-search.git $HOME/GIT/config/zsh-history-substring-search }
source ~/GIT/config/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey "^[OA" history-substring-search-up
bindkey "^[OB" history-substring-search-down

source ~/.shell/zsh/ohmy.sh
source ~/.shell/zsh/kris.zsh-theme

export EDITOR='nvim'

LESS+=" --no-init --quit-if-one-screen"

# Explicit overrides for st terminal (application mode vs normal mode arrow codes)
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

source ~/.shell/zsh/aliases.zsh
source ~/.shell/shell_aliases
source ~/.shell/shell_functions

[[ -f ~/.config/nvim/.shell_nvim ]] && source ~/.config/nvim/.shell_nvim
[[ -f ~/.local_shell_config ]] && source ~/.local_shell_config

export PATH=~/scripts:$PATH
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

hash rg 2>/dev/null && export FZF_DEFAULT_COMMAND='rg --files --hidden --glob=!.git'

# Edit command line in vim with Space in normal mode
bindkey -M vicmd ' ' edit-command-line

if [ -f ~/scripts/stop_zettel ]; then
    [ -f ~/scripts/show_todo_list ] && ~/scripts/show_todo_list
else
    [ -f ~/scripts/show_rand_zettel ] && ~/scripts/show_rand_zettel && touch ~/scripts/stop_zettel
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export TERM=st-256color
export COLORTERM=truecolor
